// Higher Poll Rate
#define USB_POLLING_INTERVAL_MS 1

//Neat RGB effex
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_KEYPRESSES
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SPLASH
    #define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif